"""Add water_intake to DailyLog

Revision ID: 5d5183f13bc9
Revises: 9732859a4cae
Create Date: 2026-05-06 19:06:46.616862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5183f13bc9'
down_revision = '9732859a4cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_intake', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_column('water_intake')

    # ### end Alembic commands ###
