"""add fitness_program to health_profile

Revision ID: 69282fdd5291
Revises: 8c374afe4f66
Create Date: 2026-05-10 12:59:50.416918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69282fdd5291'
down_revision = '8c374afe4f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitness_program', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_column('fitness_program')

    # ### end Alembic commands ###
