"""Add weight_data to Workout

Revision ID: 7c269775511f
Revises: dfc5559d1a3e
Create Date: 2026-05-08 18:38:30.250479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c269775511f'
down_revision = 'dfc5559d1a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('weight_data')

    # ### end Alembic commands ###
