"""change target_reps to string

Revision ID: 83cd9607eccb
Revises: 7f873ca7adf5
Create Date: 2026-05-10 18:15:10.055920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cd9607eccb'
down_revision = '7f873ca7adf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.alter_column('target_reps',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercises', schema=None) as batch_op:
        batch_op.alter_column('target_reps',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
