"""Add prompt_text to log_entries

Revision ID: 88991488930f
Revises: 5d5183f13bc9
Create Date: 2026-05-08 18:02:58.876362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88991488930f'
down_revision = '5d5183f13bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_column('prompt_text')

    # ### end Alembic commands ###
