"""Add gamification fields to HealthProfile

Revision ID: 8c374afe4f66
Revises: 97e78aa0802d
Create Date: 2026-05-08 22:00:17.333330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c374afe4f66'
down_revision = '97e78aa0802d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_streak_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_nutri_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_profiles', schema=None) as batch_op:
        batch_op.drop_column('last_nutri_score')
        batch_op.drop_column('last_streak_date')
        batch_op.drop_column('streak_count')

    # ### end Alembic commands ###
