"""increase_password_hash_length

Revision ID: 9732859a4cae
Revises: 26d5a5705f1d
Create Date: 2026-05-05 16:48:17.750392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9732859a4cae'
down_revision = '26d5a5705f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128, collation='Turkish_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128, collation='Turkish_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
